// <auto-generated />
using System;
using Galerie_Arta_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galerie_Arta_Web.Migrations
{
    [DbContext(typeof(Galerie_Arta_WebContext))]
    [Migration("20240111155750_TabelaUtilizator")]
    partial class TabelaUtilizator
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Galerie_Arta_Web.Models.Artist", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime?>("DataDeces")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNasterii")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationalitate")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("Galerie_Arta_Web.Models.Programare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TablouID")
                        .HasColumnType("int");

                    b.Property<int?>("UtilizatorID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TablouID");

                    b.HasIndex("UtilizatorID");

                    b.ToTable("Programare");
                });

            modelBuilder.Entity("Galerie_Arta_Web.Models.Tablou", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("ArtistID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_realizare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensiune")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.HasIndex("ArtistID");

                    b.ToTable("Tablou");
                });

            modelBuilder.Entity("Galerie_Arta_Web.Models.Utilizator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nr_telefon")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utilizator");
                });

            modelBuilder.Entity("Galerie_Arta_Web.Models.Programare", b =>
                {
                    b.HasOne("Galerie_Arta_Web.Models.Tablou", "Tablou")
                        .WithMany("Programari")
                        .HasForeignKey("TablouID");

                    b.HasOne("Galerie_Arta_Web.Models.Utilizator", "Utilizator")
                        .WithMany("Programari")
                        .HasForeignKey("UtilizatorID");

                    b.Navigation("Tablou");

                    b.Navigation("Utilizator");
                });

            modelBuilder.Entity("Galerie_Arta_Web.Models.Tablou", b =>
                {
                    b.HasOne("Galerie_Arta_Web.Models.Artist", "Artist")
                        .WithMany("Tablouri")
                        .HasForeignKey("ArtistID");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Galerie_Arta_Web.Models.Artist", b =>
                {
                    b.Navigation("Tablouri");
                });

            modelBuilder.Entity("Galerie_Arta_Web.Models.Tablou", b =>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("Galerie_Arta_Web.Models.Utilizator", b =>
                {
                    b.Navigation("Programari");
                });
#pragma warning restore 612, 618
        }
    }
}
